---
- name: K8SOPS | Download & install kubectl binary from website
  get_url:
    url: "{{ k8sops_kubectl_url | replace(' ', '') }}"
    dest: /usr/local/bin/kubectl
    mode: '0555'
    owner: root
    group: root
