---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Wait for systemd to complete initialization.
      command: systemctl is-system-running
      register: systemctl_status
      until: "'running' in systemctl_status.stdout"
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
  tasks:
    - name: "Include xat.k8sops"
      include_role:
        name: "xat.k8sops"
